### ISSUE TITLE
Sorting always happens on primary key in resource

### ISSUE THREAD

**Issue by cwdt** [woohoolabs/yin#18]
In the WoohooLabs\Yin\JsonApi\Schema\Data\CollectionData class a ksort is performed on the $ids.
I want to order the results the way I setup my SQL (using an 'order by') but this ksort is causing unexpected behaviour. Am I missing something?

**Comment by kocsismate** [comment]
Thanks for the report! I have to say that your concerns are totally valid, this behaviour definitely needs to be fixed.

That's why in my last commit (https://github.com/woohoolabs/yin/commit/c0ede5a99a9f4ca1c7c6c2ce4e459391182a4e31) I significantly reworked how primary and included resources are stored and retrieved. Additionally, as at least 2 `ksort()` invocations are avoided when returning a collection of resources, this implementation should be faster then the old one. I'll try to discover how much performance gain Yin got.

Furthermore, please review if my commit solved your problem.

**Comment by kocsismate** [comment]
I played a little bit with Blackfire: after profiling my PHP 7 app running on Amazon ECS, the benchmarks showed ~1% improvement in wall time and ~3% in CPU time for listing 100 users with complex data. This is not bad, but let's hope for the measurement being correct. :P

**Comment by cwdt** [comment]
Thanks for your quick fix, tested and works :+1:! I see positive thing happening in performance too, great!

**Comment by kocsismate** [comment]
v0.10.4 has just been released!
