### ISSUE TITLE
Relationship not in `include` parameter nor `getDefaultRelationships()` is still being evaluated

### ISSUE THREAD

**Issue by wecc** [woohoolabs/yin#2]
I'm unsure if this is the intended behavior or not but I was a bit surprised to discover that relationships returned by the transform's `getRelationships()` method are still being evaluated even though the relationship name is not present in the `include` query parameter nor in the array returned from the transform's `getDefaultRelationships()`.

I did a bit of digging and found that when a relationship is being transformed there's a check [here](https://github.com/woohoolabs/yin/blob/0f228ff6df7cfd0c12a239be5822ab001d949ac3/src/JsonApi/Transformer/AbstractResourceTransformer.php#L195-L196) that calls both `isIncludedField()` and `isIncludedRelationship()` to figure out if the relationship should be transformed or not.

However, `isIncludedField()` returns `true` since the default behavior for fields is to be included if no fields are present in the `fields` query parameter, causing the the check to fail and transform to continue.

My assumption would be that if my transformer has two relationships defined in `getRelationships()` and only one of them in `getDefaultRelationships()`, both relationships should not be evaluated.

**Comment by kocsismate** [comment]
Hey,

Thanks for the report! This part was difficult to implement (that's why it is a bit complicated), but I think the current behaviour should be in line with the specification.

The [examples page](http://jsonapi.org/examples/) of the specification covers this topic very well: the most important part is when it mentions that relationships are fields too, so the response will contain all of them by default (when you don't define sparse fieldsets). Of course, included resources will only be present if you explicitly ask for them (via the "include" query param) or define a relationship to be included by default via the `getDefaultRelationships()`.

So I believe that your confusion comes from the name of the `getDefaultRelationships()` method. It should rather be `getDefaultIncludedRelationships()` or something similar (feel free to suggest a better name!).

I hope that I understood you well. Tell me, if you meant something else. However, I tested my API, and it worked the way I expect to be correct. To avoid such confusion, I will rename this method and add some documentation for it.

**Comment by wecc** [comment]
Thank you for your reply!

Yes, I fully understand this is a complex area of the spec :)

I agree with you. Relationships, as available under the `relationships` key of a Resource Object, should be considered fields as well. Renaming `getDefaultRelationships()` to `getDefaultIncludedRelationships()` does make sense and would have caused less confusion on my part.

I think it makes sense to always include all relationship fields (unless `fields` parameter is provided and states otherwise). I do however think that it's a common scenario is to provide only `links.related` for your relationship, _unless_ you've specifically asked for the data using `included`. In that case, you already have the data and would most likely want to provide `data` for the relationship too. Do you have any suggestions how this would be handled using yin?

I failed to mention before that I greatly appreciate your effort creating this library. It seems very well written and well tested and I'm looking forward to exploring it more :+1:

**Comment by kocsismate** [comment]
Ah, really good question! I am afraid there is no workaround for it currently, however it definitely makes sense. I'll try to come up with a good solution (or you can send a PR if you have one).

Anyway, my first idea to solve this issue is to provide an `isIncluded` argument for the anonymous functions in the `getRelationships()` method and the end user can decide upon it to add the data part or not. However, you have to write an `if` statement for each relationship this way.

Another idea is to add an `omitDataIfNotIncluded()` method (or the like of it) to the `AbstractRelationship` object and it should make the decision instead of the end user. It is much cleaner, although it blocks the possibility to lazily load related resource identifier objects (so only load them when they are needed). In spite of this, I might prefer this solution. What about you?

Aand thanks for the compliments, I am glad that you found Yin to be useful. :)

**Comment by wecc** [comment]
Got it, thanks :)

For me personally, in my current project, there's a large set of resource types and relationships and performance/lazy loading is very important due to some of our back-end systems having pretty high latency. In these cases it would be golden to be able to load them only when requested.

The `isIncluded` approach would allow for lazy loading but like you said, you would have to manually handle it for every relationships. What do you think about passing `$data` as a callable to `AbstractRelationship` and that could be used in conjunction with `omitDataIfNotIncluded()`?

**Comment by kocsismate** [comment]
Yes, this was my third alternative, but I rejected it immediately as I first felt it overcomplication. But after learning about your use-case, I now think it is a viable solution!

So a `dataAsCallable()` method could be added to the relationships and as you said, it can be used along with `omitDataIfNotIncluded()`. The drawback of the solution is that users have to call two methods to perform one task.

Another idea I came up with is to add a `setDataWhenIncluded()` and a `setDataAsCallableWhenIncluded()` to the relationships. It definitely offers a simpler usage than the first one, but limits customization (`omitDataIfNotIncluded()` might be called depending on several other factors).

Now I am a bit unsure which solution I prefer (ok, maybe I like the second one more). Could you tell me your preference?

**Comment by kocsismate** [comment]
I've just implemented the first solution in my last commit (https://github.com/woohoolabs/yin/commit/6c8f328e2467e6b7cb08c5f09a5b2a6189e20c97), because I think the `setDataWhenIncluded()` method names wouldn't have been expressive enough. I hope that
you are OK with this!

P.S.: I am considering a bigger change in Yin: swapping the `Links` object with a plain-old PHP array because I became uncertain recently if an object is really useful and needed. Could you give me your input about this idea?

**Comment by wecc** [comment]
Sorry for my delayed response. I just tried out `master` and `setDataAsCallable()` solves my issue perfectly! Very appreciated, thanks a lot!

Feel free to close this issue :+1: 

## 

I think the current `Links` schema is pretty straight forward and provides a nice API. That said, I haven't used it enough to confidently know about the advantages/disadvantages compared to a plain array.
