### ISSUE TITLE
Default value will be used it the value of the request body data field is null

### ISSUE THREAD

**Issue by emil-nasso** [woohoolabs/yin#31]
I just had a look at this commit: 
https://github.com/woohoolabs/yin/commit/c2ace26d24710ac407b30a4da481deb806f44ff8#diff-8b9b082f8f14fc68d1683252b988283eR486

Won't that cause an issue when you send null as the value? Like in this case: http://jsonapi.org/format/#crud-updating-to-one-relationships

``` http
PATCH /articles/1/relationships/author HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "data": null
}
```

Would perhaps be better to use the `array_key_exists` method.

**Comment by kocsismate** [comment]
I am not sure if it is a problem.

The current implementation can be advantageous for the following use-case:

``` php
$data = $jsonApi->getRequest()->getResource([]);
hydrate($data);

function hydrate(array $data) {
    //...
}
```

because type hinting is easier as you don't have to specify a `null` default value for the `$data` parameter.

However, JSON API POST and PATCH requests must always contain a `data` object, so the question is the following: should `$request->getResource()` make difference between a valid request which removes a relationship and an invalid request which doesn't have a `data` object.

I don't have a clear answer here because I don't like when getters make validation as a "bonus" but maybe these two cases should really be distinguished. On the other hand, the current approach makes type hinting really convenient and there are other ways to validate if the request is valid (e.g.: with the `RequestValidator` class).

What is your stance on this?

**Comment by kocsismate** [comment]
I am closing this, but feel free to reopen the issue if you have further concerns about my reasoning. :)
