### ISSUE TITLE
Cannot install via composer

### ISSUE THREAD

**Issue by ghost** [woohoolabs/yin#32]
Hi,

I cannot install the package via composer

```
composer require woohoolabs/yin
```

Here is the error

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for woohoolabs/yin ^0.10.8 -> satisfiable by woohoolabs/yin[0.10.8].
    - woohoolabs/yin 0.10.8 requires psr/http-message-implementation ^1.0.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

```

**Comment by kocsismate** [comment]
Hey,

Unfortunately, Composer's error message isn't really informative, but the problem is that Yin requires a PSR-7 implementation (a package which provides the http-message-implementation [virtual package](https://devedge.wordpress.com/2014/09/27/composer-and-virtual-packages/)) and it seems that you haven't installed one yet. You may use `zendframework/zend-diactoros` for this purpose. :)

I'll update the read me file with the solution! Thanks for pointing out the problem.

**Comment by ghost** [comment]
Now it works like a charm :) Thanks
