### ISSUE TITLE
Custom Responder, Document without Response and some more.

### ISSUE THREAD

**Issue by lunika** [woohoolabs/yin#53]
Hi,

I use this library for the last 2 weeks, it helps me a lot and I would like to discuss with you about some choice you made and understand why.

First of all, why did you choose to create the `Responder` in the `JsonApi` class ? it makes hard to create our own responder because it is not possible to use it with the original `JsonApi` class. Doing this, we have 2 choices : 
- extends `JsonApi` class and change its behaviour
- use directly our own reponder. After all the `JsonApi` class is just a factory which instanciate a new `Responder` injecting a `Request`, a `Response`, an `ExceptionFactory` and a `Serializer`.

Secondly, why did you choose to couple the `Document` witht the `serializer` ? AFAIK the `serializer` is only here to hydrate the `Response`, it doesn't transform the `Document` in a JsonApi content. It should be great to remove the response in the Document transformation process, I think it's more the Responder responsability to do this. The Responder receive a Document, transform it and then hydrate the response and return it. Just like you did with the Hydrator.

I would be happy to discuss about that and if you want I can help by providing a PoC, contribute to the library, etc.

**Comment by kocsismate** [comment]
First of all, thank you very much for these insights :) I'll answer your questions below:

1.) I chose it to be hard-coded because at that time I didn't think there was use of making it extendible. But now I became curious what aspects of the `Responder` class you want to change? Anyway, I'd pleasingly make it available as a dependency of the `JsonApi` class if it helps you (and the `RelationshipResponder` class has to be cared about, too). :)

2.) This question is a bit more difficult to answer. I believe the reason of coupling the `Document` and `SerializerInterface` was the following:

When I started the project my idea was that documents should be able to be transformed to PSR-7 responses. Seemingly, this decision had the advantage that `Document`s could be used in themselves, without classes like `JsonApi` or `Responder`. But later on, `Serializer`s appeared and there wasn't any possibility not to couple them to documents anymore.

In essence, I do think that decoupling things from documents is a good idea as `AbstractDocument` et all are rather complicated because there are too many ways they are consumed.

So if one would like to move serialization outside of `Document`s then `getResponse()` et all methods should be renamed to `transform()` et all which return an array containing the JSON:API document. Unfortunately, only one line per method can be saved this way (typically: `return $serializer->serialize($response, $responseCode, $content);`).

That said, I don't see now much sense to decouple documents from serialization because documents wouldn't become much cleaner when doing so, and unfortunately, I don't have a better design in mind for document transformation. But I am eager to listen to your ideas and suggestions. :) And of course, I'd be curious what the benefit would be for you if these classes were decoupled from each other.

**Comment by lunika** [comment]
> 1.) I chose it to be hard-coded because at that time I didn't think there was use of making it extendible. But now I became curious what aspects of the Responder class you want to change? Anyway, I'd pleasingly make it available as a dependency of the JsonApi class if it helps you (and the RelationshipResponder class has to be cared about, too). :)

finally I didn't extend nor use it anymore, I will explain why in the next point ;-)

> I'd be curious what the benefit would be for you if these classes were decoupled from each other.

In fact I don't need to transform the document in a response, I already have a responder service and is role is to elect the good responder depending many parameters and my responder allow me to set all the headers I want, which is not the case with the reponder in this library

To fit my need I rewrote all the abstract document and removed the serializer in it. For example in my AbstractSuccessfulDocument I have a `getContent` instead of `getResponse` method : 
```php
    /**
     *
     * @param \WoohooLabs\Yin\JsonApi\Request\RequestInterface $request
     * @param \WoohooLabs\Yin\JsonApi\Exception\ExceptionFactoryInterface $exceptionFactory
     * @param mixed $domainObject
     * @param int $responseCode
     * @param array $additionalMeta
     * @return array
     */
    public function getContent(
        RequestInterface $request,
        ExceptionFactoryInterface $exceptionFactory,
        $domainObject,
        array $additionalMeta = []
    ): array {
        $transformation = new Transformation($request, $this->createData(), $exceptionFactory, "");

        $this->initializeDocument($domainObject);

        return $this->transformContent($transformation, $additionalMeta);
    }
```

Doing this the only role of the document is to take a domainObject and format it in a jsonapi format. That's all. And I think the serializer should be used only in the responder. I need a response ? I use the responder which use the serializer and the content transformed from the document. I don't need it ? I use the document alone.

WDYT about this way to think the library ? Each part is responsible to do only one thing :
- a document to format a resource in jsonapi format (return an array)
- the serializer to create the response (return a Response)
- the responder will have helper to create a reponse (like now)
It will be still possible to use the library from one entry point, the `JsonApi` class or to use only the component you want which is not reall possible for now.

**Comment by kocsismate** [comment]
As you have probably noticed, I've just merged your PR. Thank you very much! I'll finish the work with the `Error` classes :)

**Comment by lunika** [comment]
Great 👍 

For version 2.0 if you want you can open issue and tag them, I can help you if you want.
