### ISSUE TITLE
Allow to set options to the json_encode method

### ISSUE THREAD

**Issue by lunika** [woohoolabs/yin#58]
It should be great to configure a little bit how the `json_encode` method is used in the Serializer. Configure all the options and the depth.
You can maybe add this in your v2 roadmap ? :-)

**Comment by kocsismate** [comment]
Yeah, for sure. Good idea! I'll release a beta version tonight with this change.

And I plan to include the changes for hydrators in the second beta so we can think about the implementation a little bit more.

**Comment by kocsismate** [comment]
I've just released 2.0.0-beta1 with this change (https://github.com/woohoolabs/yin/commit/f263ea9ac532b2a1d125e9d0cf0264fef8a8db26) :) I hope you'll like it - apart from some breaking changes which need some time to be resolved. Feel free to reach out to me if you might need help.

And do not hesitate to share other ideas of yours which come with breaking changes. I plan to stay in beta/RC for some weeks in order to accumulate enough ideas.

**Comment by lunika** [comment]
Thanks, I will test this soon :-)

**Comment by leclairmael** [comment]
Hello,
That's an interesting feature, could you backport it to the 1.0 branch?

**Comment by kocsismate** [comment]
Hi,

It's done by now :) And I've just released v1.0.5!
