### ISSUE TITLE
Example how to grab a sub-resource.

### ISSUE THREAD

**Issue by mmucklo** [woohoolabs/yin#7]
It seems you have examples on how to do:

/books/{id}

and 

/books/{id}/relationships/authors

But not:

/books/{id}/authors

Unless I'm missing something?  Do you natively support this type of call?

**Comment by kocsismate** [comment]
I believe this type of call should be out of the scope of the project, because it's more efficient, yet really easy to implement by yourself.

When a client requests the authors of a book, you only need to get the appropriate authors from your DB and respond with a document whose primary data is the collection of the aformentioned authors.

I don't know if you have read this page, but I think it highlights the difference between "relationships" and "related resources": http://jsonapi.org/recommendations/#urls-relationships

Thanks for bringing this question up, I just have added a new example for the use-case to dev-master. :)

**Comment by kocsismate** [comment]
@mmucklo: Did my reasoning make sense? If so, could you please close the issue? Otherwise, feel free to ask more!

**Comment by mmucklo** [comment]
I tested the example and it works except I think I have a question on the URL.

(BTW, I apologize my original question had some tags in it that weren't showing, fixed)

So the self: link in your example shows **"self": "/books/authors"** even though my query is **example=book-authors&book-id=1**.

Shouldn't it be (at the very least) **"/books/1/authors"**?

**Comment by kocsismate** [comment]
Yes, it should definitely be at the very least "/books/1/authors"! The current URL structure is really "clunky" indeed, but only because I did not want to require users to setup their web server for a more clever routing system in order to be able to try the examples.

**Comment by kocsismate** [comment]
Please have look at the [How to try it out section in the readme](https://github.com/woohoolabs/yin/blob/master/README.md#how-to-try-it-out), because I think I managed to fix the issues noted in this thread:  :)

**Comment by mmucklo** [comment]
ok, I'll have to retest.  Please stand by...

**Comment by mmucklo** [comment]
tested, looks good.  Thanks, I'll reopen if there's anything further regarding this issue, but for now I think we're good.

Thanks for the responses!
